gmail:
  client_id: "${GMAIL_CLIENT_ID}"
  client_secret: "${GMAIL_CLIENT_SECRET}"
  token_file: "data/gmail_token.json"
  scopes:
    - "https://www.googleapis.com/auth/gmail.readonly"
    - "https://www.googleapis.com/auth/gmail.modify"
  batch_size: 100
  rate_limit: 250
  timeout: 30s
  retry_attempts: 3
  retry_delay: 1s

ollama:
  base_url: "http://127.0.0.1:11434"
  default_model: "qwen2.5:latest"
  timeout: 30s
  max_retries: 3
  request_timeout: 30s
  health_check_period: 60s
  circuit_breaker:
    max_requests: 10
    interval: 60s
    timeout: 60s
    ready_to_trip: 5

profiles:
  directory: "profiles"
  resolver_config: "profiles/resolver.yaml"
  reload_interval: 5m
  validate_on_load: true
  cache_enabled: true

audit:
  enabled: true
  directory: "data/audit"
  max_file_size: 104857600  # 100MB
  max_files: 10
  rotation_period: 24h
  integrity_check: true
  encryption_key: "${AUDIT_ENCRYPTION_KEY}"

security:
  encryption_key: "${ENCRYPTION_KEY}"
  token_encryption: true
  input_sanitization: true
  max_email_size: 10485760  # 10MB
  max_batch_size: 1000

server:
  port: 8080
  read_timeout: 15s
  write_timeout: 15s
  max_header_bytes: 1048576  # 1MB
  enable_profiling: false
